version: '3.3'

services:
  reverse-proxy-balancer-sticky-rr:
    image: 'res/apache-rp-balancer-sticky-rr'
    build:
      context: 'images/reverse-proxy'
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
  static1:
    image: 'res/apache_php'
    build:
      context: 'images/static-php'
      dockerfile: ./Dockerfile
  static2:
    image: 'res/apache_php'
    build:
      context: 'images/static-php'
      dockerfile: ./Dockerfile
  static3:
    image: 'res/apache_php'
    build:
      context: 'images/static-php'
      dockerfile: ./Dockerfile
  dynamic1:
    image: 'res/express'
    build:
      context: 'images/dynamic-express'
      dockerfile: ./Dockerfile
  dynamic2:
    image: 'res/express'
    build:
      context: 'images/dynamic-express'
      dockerfile: ./Dockerfile
  dynamic3:
    image: 'res/express'
    build:
      context: 'images/dynamic-express'
      dockerfile: ./Dockerfile
